In [40]:
import numpy as np

In [3]:
array=np.array([1,2,3])
print(array)

[1 2 3]


In [4]:
array.shape

(3,)

In [5]:
array2=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
array2.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [6]:
array2.ndim

1

In [7]:
array.dtype.name

'int32'

In [8]:
array2.size

15

In [9]:
type(array)

numpy.ndarray

In [10]:
array3=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
array3


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
array3.shape

(3, 5)

In [12]:
zeros=np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.empty((4,5))

array([[6.01347002e-154, 1.01766150e-028, 4.28358189e+170,
        4.81431726e+199, 9.78749662e+199],
       [6.24277977e+228, 1.69337243e-152, 6.01347002e-154,
        6.19750796e+223, 8.87663377e+247],
       [4.82412327e+228, 6.01347157e-154, 6.01347002e-154,
        6.01347002e-154, 3.17059623e+180],
       [6.45866048e+170, 8.89486967e+252, 9.08367237e+223,
        1.03983890e-152, 6.01347002e-154]])

In [15]:
np.arange(10,50,5) #aralık veriyoruz

array([10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
np.linspace(0,10,20) #burda sayı üretiyoruz

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)

[5 7 9]
[-3 -3 -3]


In [20]:
liste =[1,2,3,4,5]
array4=np.array([1,2,3,4,5])
print(liste)
print(array4)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [22]:
array=np.array(liste)
print(array)

[1 2 3 4 5]


In [9]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [12]:
b=a
c=a
b[0]=5
print(a,b,c) #numpy array is not stored as a value in memory,it is stored as a space.

[5 2 3] [5 2 3] [5 2 3]


In [16]:
a =np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
print(a[0])

1


In [18]:
print(a[0:4]) #4 dahil olmaz

[1 2 3 4]


In [20]:
print(a[::-1])

[7 6 5 4 3 2 1]


In [25]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b[1,1])

7


In [26]:
print(b[:,1])

[2 7]


In [27]:
print(b[1,:]) #ilk bölüm satır ikinci bölüm sütun

[ 6  7  8  9 10]


In [29]:
print(b[1,1:4])

[7 8 9]


In [30]:
print(b[-1 ,:])

[ 6  7  8  9 10]


In [31]:
print(b[:,-1])

[ 5 10]


In [32]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
b=a.ravel()
b  #bu method matrisi tekrar vektör haline getirir

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
b.reshape(3,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [43]:
b  #reshape fonkisiyonuyla yapılan matrisler kalıcı değildir o yüzden resize fonkisyonu kullanılır

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [45]:
b.resize(3,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [46]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])